apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: cloudmart
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: cloudmart
spec:
  type: ClusterIP
  ports:
    - port: 8009
      targetPort: 8009
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: analytics-service
