# Template for Kubernetes Core Secrets
# In production, secrets are dynamically mounted via HashiCorp Vault CSI Driver.
apiVersion: v1
kind: Secret
metadata:
  name: cloudmart-core-secrets
  namespace: cloudmart
type: Opaque
stringData:
  DATABASE_PASSWORD: ""
  JWT_SIGNING_KEY: ""
  PAYMENT_TOKEN: ""
  PAYPAL_SECRET: ""
  KAFKA_PASSWORD: ""
  REDIS_PASSWORD: ""
