apiVersion: v1
kind: Secret
metadata:
  name: cloudmart-core-secrets
  namespace: cloudmart
type: Opaque
stringData:
  DATABASE_PASSWORD: "vault_managed_db_password_ref"
  JWT_SECRET_KEY: "vault_managed_jwt_signing_key_ref"
  STRIPE_API_KEY: "vault_managed_stripe_token_ref"
  PAYPAL_CLIENT_SECRET: "vault_managed_paypal_secret_ref"
  KAFKA_SASL_PASSWORD: "vault_managed_kafka_password_ref"
  REDIS_PASSWORD: "vault_managed_redis_password_ref"
