apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: cloudmart
  labels:
    app.kubernetes.io/name: shipping-service
    app.kubernetes.io/part-of: cloudmart
spec:
  type: ClusterIP
  ports:
    - port: 8007
      targetPort: 8007
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: shipping-service
