"""Automated Test Fixtures and Synthetic Data Generators for API Gateway Service."""

import uuid
import random
import string
from typing import Any, Dict, List
from services.api_gateway.domain.models import GatewayRouteAggregate, RoutePredicate, RouteFilter
from services.api_gateway.dto.requests import CreateGatewayRouteRequest, AddRoutePredicateRequest, AddRouteFilterRequest

class GatewayRouteFixtureFactory:
    """Generates deterministic mock domain objects and DTOs for testing."""

    @staticmethod
    def make_aggregate(name_prefix: str = "Test", code_prefix: str = "CODE") -> GatewayRouteAggregate:
        uid = "".join(random.choices(string.ascii_uppercase + string.digits, k=6))
        return GatewayRouteAggregate(
            name=f"{name_prefix} Item {uid}",
            code=f"{code_prefix}-{uid}",
            description="Synthetic test aggregate instance",
            status="DRAFT",
            category="STANDARD",
            attributes={"env": "test", "seed": True, "weight": 10.5}
        )

    @staticmethod
    def make_create_request() -> CreateGatewayRouteRequest:
        rand_id = random.randint(1000, 9999)
        return CreateGatewayRouteRequest(
            name=f"Factory GatewayRoute {rand_id}",
            code=f"FAC-{rand_id}",
            description="Generated via fixture factory",
            category="FACTORY"
        )

    @staticmethod
    def make_sub1(parent_id: str) -> RoutePredicate:
        rand_code = "".join(random.choices(string.ascii_uppercase, k=4))
        return RoutePredicate(
            name=f"Sub1 Item {rand_code}",
            code=f"S1-{rand_code}",
            priority=random.randint(1, 50)
        )

    @staticmethod
    def make_sub2(parent_id: str) -> RouteFilter:
        rand_label = "".join(random.choices(string.ascii_uppercase, k=5))
        return RouteFilter(
            label=f"Sub2 Label {rand_label}",
            value_payload=f"Payload for {rand_label}",
            score=round(random.uniform(1.0, 100.0), 2)
        )

FIXTURE_DATASET: List[Dict[str, Any]] = [
    {
        "id": "fixture-api_gateway-0001",
        "name": "API Gateway Service Benchmark Sample 1",
        "code": "BMK-API-0001",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_1_1",
            "prop_2": "val_1_2",
            "prop_3": "val_1_3",
            "prop_4": "val_1_4",
            "prop_5": "val_1_5",
            "prop_6": "val_1_6",
            "prop_7": "val_1_7",
            "prop_8": "val_1_8",
            "prop_9": "val_1_9",
            "prop_10": "val_1_10",
            "prop_11": "val_1_11",
            "prop_12": "val_1_12",
            "prop_13": "val_1_13",
            "prop_14": "val_1_14",
            "index": 1,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0002",
        "name": "API Gateway Service Benchmark Sample 2",
        "code": "BMK-API-0002",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_2_1",
            "prop_2": "val_2_2",
            "prop_3": "val_2_3",
            "prop_4": "val_2_4",
            "prop_5": "val_2_5",
            "prop_6": "val_2_6",
            "prop_7": "val_2_7",
            "prop_8": "val_2_8",
            "prop_9": "val_2_9",
            "prop_10": "val_2_10",
            "prop_11": "val_2_11",
            "prop_12": "val_2_12",
            "prop_13": "val_2_13",
            "prop_14": "val_2_14",
            "index": 2,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0003",
        "name": "API Gateway Service Benchmark Sample 3",
        "code": "BMK-API-0003",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_3_1",
            "prop_2": "val_3_2",
            "prop_3": "val_3_3",
            "prop_4": "val_3_4",
            "prop_5": "val_3_5",
            "prop_6": "val_3_6",
            "prop_7": "val_3_7",
            "prop_8": "val_3_8",
            "prop_9": "val_3_9",
            "prop_10": "val_3_10",
            "prop_11": "val_3_11",
            "prop_12": "val_3_12",
            "prop_13": "val_3_13",
            "prop_14": "val_3_14",
            "index": 3,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0004",
        "name": "API Gateway Service Benchmark Sample 4",
        "code": "BMK-API-0004",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_4_1",
            "prop_2": "val_4_2",
            "prop_3": "val_4_3",
            "prop_4": "val_4_4",
            "prop_5": "val_4_5",
            "prop_6": "val_4_6",
            "prop_7": "val_4_7",
            "prop_8": "val_4_8",
            "prop_9": "val_4_9",
            "prop_10": "val_4_10",
            "prop_11": "val_4_11",
            "prop_12": "val_4_12",
            "prop_13": "val_4_13",
            "prop_14": "val_4_14",
            "index": 4,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0005",
        "name": "API Gateway Service Benchmark Sample 5",
        "code": "BMK-API-0005",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_5_1",
            "prop_2": "val_5_2",
            "prop_3": "val_5_3",
            "prop_4": "val_5_4",
            "prop_5": "val_5_5",
            "prop_6": "val_5_6",
            "prop_7": "val_5_7",
            "prop_8": "val_5_8",
            "prop_9": "val_5_9",
            "prop_10": "val_5_10",
            "prop_11": "val_5_11",
            "prop_12": "val_5_12",
            "prop_13": "val_5_13",
            "prop_14": "val_5_14",
            "index": 5,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0006",
        "name": "API Gateway Service Benchmark Sample 6",
        "code": "BMK-API-0006",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_6_1",
            "prop_2": "val_6_2",
            "prop_3": "val_6_3",
            "prop_4": "val_6_4",
            "prop_5": "val_6_5",
            "prop_6": "val_6_6",
            "prop_7": "val_6_7",
            "prop_8": "val_6_8",
            "prop_9": "val_6_9",
            "prop_10": "val_6_10",
            "prop_11": "val_6_11",
            "prop_12": "val_6_12",
            "prop_13": "val_6_13",
            "prop_14": "val_6_14",
            "index": 6,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0007",
        "name": "API Gateway Service Benchmark Sample 7",
        "code": "BMK-API-0007",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_7_1",
            "prop_2": "val_7_2",
            "prop_3": "val_7_3",
            "prop_4": "val_7_4",
            "prop_5": "val_7_5",
            "prop_6": "val_7_6",
            "prop_7": "val_7_7",
            "prop_8": "val_7_8",
            "prop_9": "val_7_9",
            "prop_10": "val_7_10",
            "prop_11": "val_7_11",
            "prop_12": "val_7_12",
            "prop_13": "val_7_13",
            "prop_14": "val_7_14",
            "index": 7,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0008",
        "name": "API Gateway Service Benchmark Sample 8",
        "code": "BMK-API-0008",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_8_1",
            "prop_2": "val_8_2",
            "prop_3": "val_8_3",
            "prop_4": "val_8_4",
            "prop_5": "val_8_5",
            "prop_6": "val_8_6",
            "prop_7": "val_8_7",
            "prop_8": "val_8_8",
            "prop_9": "val_8_9",
            "prop_10": "val_8_10",
            "prop_11": "val_8_11",
            "prop_12": "val_8_12",
            "prop_13": "val_8_13",
            "prop_14": "val_8_14",
            "index": 8,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0009",
        "name": "API Gateway Service Benchmark Sample 9",
        "code": "BMK-API-0009",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_9_1",
            "prop_2": "val_9_2",
            "prop_3": "val_9_3",
            "prop_4": "val_9_4",
            "prop_5": "val_9_5",
            "prop_6": "val_9_6",
            "prop_7": "val_9_7",
            "prop_8": "val_9_8",
            "prop_9": "val_9_9",
            "prop_10": "val_9_10",
            "prop_11": "val_9_11",
            "prop_12": "val_9_12",
            "prop_13": "val_9_13",
            "prop_14": "val_9_14",
            "index": 9,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0010",
        "name": "API Gateway Service Benchmark Sample 10",
        "code": "BMK-API-0010",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_10_1",
            "prop_2": "val_10_2",
            "prop_3": "val_10_3",
            "prop_4": "val_10_4",
            "prop_5": "val_10_5",
            "prop_6": "val_10_6",
            "prop_7": "val_10_7",
            "prop_8": "val_10_8",
            "prop_9": "val_10_9",
            "prop_10": "val_10_10",
            "prop_11": "val_10_11",
            "prop_12": "val_10_12",
            "prop_13": "val_10_13",
            "prop_14": "val_10_14",
            "index": 10,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0011",
        "name": "API Gateway Service Benchmark Sample 11",
        "code": "BMK-API-0011",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_11_1",
            "prop_2": "val_11_2",
            "prop_3": "val_11_3",
            "prop_4": "val_11_4",
            "prop_5": "val_11_5",
            "prop_6": "val_11_6",
            "prop_7": "val_11_7",
            "prop_8": "val_11_8",
            "prop_9": "val_11_9",
            "prop_10": "val_11_10",
            "prop_11": "val_11_11",
            "prop_12": "val_11_12",
            "prop_13": "val_11_13",
            "prop_14": "val_11_14",
            "index": 11,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0012",
        "name": "API Gateway Service Benchmark Sample 12",
        "code": "BMK-API-0012",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_12_1",
            "prop_2": "val_12_2",
            "prop_3": "val_12_3",
            "prop_4": "val_12_4",
            "prop_5": "val_12_5",
            "prop_6": "val_12_6",
            "prop_7": "val_12_7",
            "prop_8": "val_12_8",
            "prop_9": "val_12_9",
            "prop_10": "val_12_10",
            "prop_11": "val_12_11",
            "prop_12": "val_12_12",
            "prop_13": "val_12_13",
            "prop_14": "val_12_14",
            "index": 12,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0013",
        "name": "API Gateway Service Benchmark Sample 13",
        "code": "BMK-API-0013",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_13_1",
            "prop_2": "val_13_2",
            "prop_3": "val_13_3",
            "prop_4": "val_13_4",
            "prop_5": "val_13_5",
            "prop_6": "val_13_6",
            "prop_7": "val_13_7",
            "prop_8": "val_13_8",
            "prop_9": "val_13_9",
            "prop_10": "val_13_10",
            "prop_11": "val_13_11",
            "prop_12": "val_13_12",
            "prop_13": "val_13_13",
            "prop_14": "val_13_14",
            "index": 13,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0014",
        "name": "API Gateway Service Benchmark Sample 14",
        "code": "BMK-API-0014",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_14_1",
            "prop_2": "val_14_2",
            "prop_3": "val_14_3",
            "prop_4": "val_14_4",
            "prop_5": "val_14_5",
            "prop_6": "val_14_6",
            "prop_7": "val_14_7",
            "prop_8": "val_14_8",
            "prop_9": "val_14_9",
            "prop_10": "val_14_10",
            "prop_11": "val_14_11",
            "prop_12": "val_14_12",
            "prop_13": "val_14_13",
            "prop_14": "val_14_14",
            "index": 14,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0015",
        "name": "API Gateway Service Benchmark Sample 15",
        "code": "BMK-API-0015",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_15_1",
            "prop_2": "val_15_2",
            "prop_3": "val_15_3",
            "prop_4": "val_15_4",
            "prop_5": "val_15_5",
            "prop_6": "val_15_6",
            "prop_7": "val_15_7",
            "prop_8": "val_15_8",
            "prop_9": "val_15_9",
            "prop_10": "val_15_10",
            "prop_11": "val_15_11",
            "prop_12": "val_15_12",
            "prop_13": "val_15_13",
            "prop_14": "val_15_14",
            "index": 15,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0016",
        "name": "API Gateway Service Benchmark Sample 16",
        "code": "BMK-API-0016",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_16_1",
            "prop_2": "val_16_2",
            "prop_3": "val_16_3",
            "prop_4": "val_16_4",
            "prop_5": "val_16_5",
            "prop_6": "val_16_6",
            "prop_7": "val_16_7",
            "prop_8": "val_16_8",
            "prop_9": "val_16_9",
            "prop_10": "val_16_10",
            "prop_11": "val_16_11",
            "prop_12": "val_16_12",
            "prop_13": "val_16_13",
            "prop_14": "val_16_14",
            "index": 16,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0017",
        "name": "API Gateway Service Benchmark Sample 17",
        "code": "BMK-API-0017",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_17_1",
            "prop_2": "val_17_2",
            "prop_3": "val_17_3",
            "prop_4": "val_17_4",
            "prop_5": "val_17_5",
            "prop_6": "val_17_6",
            "prop_7": "val_17_7",
            "prop_8": "val_17_8",
            "prop_9": "val_17_9",
            "prop_10": "val_17_10",
            "prop_11": "val_17_11",
            "prop_12": "val_17_12",
            "prop_13": "val_17_13",
            "prop_14": "val_17_14",
            "index": 17,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0018",
        "name": "API Gateway Service Benchmark Sample 18",
        "code": "BMK-API-0018",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_18_1",
            "prop_2": "val_18_2",
            "prop_3": "val_18_3",
            "prop_4": "val_18_4",
            "prop_5": "val_18_5",
            "prop_6": "val_18_6",
            "prop_7": "val_18_7",
            "prop_8": "val_18_8",
            "prop_9": "val_18_9",
            "prop_10": "val_18_10",
            "prop_11": "val_18_11",
            "prop_12": "val_18_12",
            "prop_13": "val_18_13",
            "prop_14": "val_18_14",
            "index": 18,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0019",
        "name": "API Gateway Service Benchmark Sample 19",
        "code": "BMK-API-0019",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_19_1",
            "prop_2": "val_19_2",
            "prop_3": "val_19_3",
            "prop_4": "val_19_4",
            "prop_5": "val_19_5",
            "prop_6": "val_19_6",
            "prop_7": "val_19_7",
            "prop_8": "val_19_8",
            "prop_9": "val_19_9",
            "prop_10": "val_19_10",
            "prop_11": "val_19_11",
            "prop_12": "val_19_12",
            "prop_13": "val_19_13",
            "prop_14": "val_19_14",
            "index": 19,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0020",
        "name": "API Gateway Service Benchmark Sample 20",
        "code": "BMK-API-0020",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_20_1",
            "prop_2": "val_20_2",
            "prop_3": "val_20_3",
            "prop_4": "val_20_4",
            "prop_5": "val_20_5",
            "prop_6": "val_20_6",
            "prop_7": "val_20_7",
            "prop_8": "val_20_8",
            "prop_9": "val_20_9",
            "prop_10": "val_20_10",
            "prop_11": "val_20_11",
            "prop_12": "val_20_12",
            "prop_13": "val_20_13",
            "prop_14": "val_20_14",
            "index": 20,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0021",
        "name": "API Gateway Service Benchmark Sample 21",
        "code": "BMK-API-0021",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_21_1",
            "prop_2": "val_21_2",
            "prop_3": "val_21_3",
            "prop_4": "val_21_4",
            "prop_5": "val_21_5",
            "prop_6": "val_21_6",
            "prop_7": "val_21_7",
            "prop_8": "val_21_8",
            "prop_9": "val_21_9",
            "prop_10": "val_21_10",
            "prop_11": "val_21_11",
            "prop_12": "val_21_12",
            "prop_13": "val_21_13",
            "prop_14": "val_21_14",
            "index": 21,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0022",
        "name": "API Gateway Service Benchmark Sample 22",
        "code": "BMK-API-0022",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_22_1",
            "prop_2": "val_22_2",
            "prop_3": "val_22_3",
            "prop_4": "val_22_4",
            "prop_5": "val_22_5",
            "prop_6": "val_22_6",
            "prop_7": "val_22_7",
            "prop_8": "val_22_8",
            "prop_9": "val_22_9",
            "prop_10": "val_22_10",
            "prop_11": "val_22_11",
            "prop_12": "val_22_12",
            "prop_13": "val_22_13",
            "prop_14": "val_22_14",
            "index": 22,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0023",
        "name": "API Gateway Service Benchmark Sample 23",
        "code": "BMK-API-0023",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_23_1",
            "prop_2": "val_23_2",
            "prop_3": "val_23_3",
            "prop_4": "val_23_4",
            "prop_5": "val_23_5",
            "prop_6": "val_23_6",
            "prop_7": "val_23_7",
            "prop_8": "val_23_8",
            "prop_9": "val_23_9",
            "prop_10": "val_23_10",
            "prop_11": "val_23_11",
            "prop_12": "val_23_12",
            "prop_13": "val_23_13",
            "prop_14": "val_23_14",
            "index": 23,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0024",
        "name": "API Gateway Service Benchmark Sample 24",
        "code": "BMK-API-0024",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_24_1",
            "prop_2": "val_24_2",
            "prop_3": "val_24_3",
            "prop_4": "val_24_4",
            "prop_5": "val_24_5",
            "prop_6": "val_24_6",
            "prop_7": "val_24_7",
            "prop_8": "val_24_8",
            "prop_9": "val_24_9",
            "prop_10": "val_24_10",
            "prop_11": "val_24_11",
            "prop_12": "val_24_12",
            "prop_13": "val_24_13",
            "prop_14": "val_24_14",
            "index": 24,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0025",
        "name": "API Gateway Service Benchmark Sample 25",
        "code": "BMK-API-0025",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_25_1",
            "prop_2": "val_25_2",
            "prop_3": "val_25_3",
            "prop_4": "val_25_4",
            "prop_5": "val_25_5",
            "prop_6": "val_25_6",
            "prop_7": "val_25_7",
            "prop_8": "val_25_8",
            "prop_9": "val_25_9",
            "prop_10": "val_25_10",
            "prop_11": "val_25_11",
            "prop_12": "val_25_12",
            "prop_13": "val_25_13",
            "prop_14": "val_25_14",
            "index": 25,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0026",
        "name": "API Gateway Service Benchmark Sample 26",
        "code": "BMK-API-0026",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_26_1",
            "prop_2": "val_26_2",
            "prop_3": "val_26_3",
            "prop_4": "val_26_4",
            "prop_5": "val_26_5",
            "prop_6": "val_26_6",
            "prop_7": "val_26_7",
            "prop_8": "val_26_8",
            "prop_9": "val_26_9",
            "prop_10": "val_26_10",
            "prop_11": "val_26_11",
            "prop_12": "val_26_12",
            "prop_13": "val_26_13",
            "prop_14": "val_26_14",
            "index": 26,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0027",
        "name": "API Gateway Service Benchmark Sample 27",
        "code": "BMK-API-0027",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_27_1",
            "prop_2": "val_27_2",
            "prop_3": "val_27_3",
            "prop_4": "val_27_4",
            "prop_5": "val_27_5",
            "prop_6": "val_27_6",
            "prop_7": "val_27_7",
            "prop_8": "val_27_8",
            "prop_9": "val_27_9",
            "prop_10": "val_27_10",
            "prop_11": "val_27_11",
            "prop_12": "val_27_12",
            "prop_13": "val_27_13",
            "prop_14": "val_27_14",
            "index": 27,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0028",
        "name": "API Gateway Service Benchmark Sample 28",
        "code": "BMK-API-0028",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_28_1",
            "prop_2": "val_28_2",
            "prop_3": "val_28_3",
            "prop_4": "val_28_4",
            "prop_5": "val_28_5",
            "prop_6": "val_28_6",
            "prop_7": "val_28_7",
            "prop_8": "val_28_8",
            "prop_9": "val_28_9",
            "prop_10": "val_28_10",
            "prop_11": "val_28_11",
            "prop_12": "val_28_12",
            "prop_13": "val_28_13",
            "prop_14": "val_28_14",
            "index": 28,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0029",
        "name": "API Gateway Service Benchmark Sample 29",
        "code": "BMK-API-0029",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_29_1",
            "prop_2": "val_29_2",
            "prop_3": "val_29_3",
            "prop_4": "val_29_4",
            "prop_5": "val_29_5",
            "prop_6": "val_29_6",
            "prop_7": "val_29_7",
            "prop_8": "val_29_8",
            "prop_9": "val_29_9",
            "prop_10": "val_29_10",
            "prop_11": "val_29_11",
            "prop_12": "val_29_12",
            "prop_13": "val_29_13",
            "prop_14": "val_29_14",
            "index": 29,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0030",
        "name": "API Gateway Service Benchmark Sample 30",
        "code": "BMK-API-0030",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_30_1",
            "prop_2": "val_30_2",
            "prop_3": "val_30_3",
            "prop_4": "val_30_4",
            "prop_5": "val_30_5",
            "prop_6": "val_30_6",
            "prop_7": "val_30_7",
            "prop_8": "val_30_8",
            "prop_9": "val_30_9",
            "prop_10": "val_30_10",
            "prop_11": "val_30_11",
            "prop_12": "val_30_12",
            "prop_13": "val_30_13",
            "prop_14": "val_30_14",
            "index": 30,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0031",
        "name": "API Gateway Service Benchmark Sample 31",
        "code": "BMK-API-0031",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_31_1",
            "prop_2": "val_31_2",
            "prop_3": "val_31_3",
            "prop_4": "val_31_4",
            "prop_5": "val_31_5",
            "prop_6": "val_31_6",
            "prop_7": "val_31_7",
            "prop_8": "val_31_8",
            "prop_9": "val_31_9",
            "prop_10": "val_31_10",
            "prop_11": "val_31_11",
            "prop_12": "val_31_12",
            "prop_13": "val_31_13",
            "prop_14": "val_31_14",
            "index": 31,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0032",
        "name": "API Gateway Service Benchmark Sample 32",
        "code": "BMK-API-0032",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_32_1",
            "prop_2": "val_32_2",
            "prop_3": "val_32_3",
            "prop_4": "val_32_4",
            "prop_5": "val_32_5",
            "prop_6": "val_32_6",
            "prop_7": "val_32_7",
            "prop_8": "val_32_8",
            "prop_9": "val_32_9",
            "prop_10": "val_32_10",
            "prop_11": "val_32_11",
            "prop_12": "val_32_12",
            "prop_13": "val_32_13",
            "prop_14": "val_32_14",
            "index": 32,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0033",
        "name": "API Gateway Service Benchmark Sample 33",
        "code": "BMK-API-0033",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_33_1",
            "prop_2": "val_33_2",
            "prop_3": "val_33_3",
            "prop_4": "val_33_4",
            "prop_5": "val_33_5",
            "prop_6": "val_33_6",
            "prop_7": "val_33_7",
            "prop_8": "val_33_8",
            "prop_9": "val_33_9",
            "prop_10": "val_33_10",
            "prop_11": "val_33_11",
            "prop_12": "val_33_12",
            "prop_13": "val_33_13",
            "prop_14": "val_33_14",
            "index": 33,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0034",
        "name": "API Gateway Service Benchmark Sample 34",
        "code": "BMK-API-0034",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_34_1",
            "prop_2": "val_34_2",
            "prop_3": "val_34_3",
            "prop_4": "val_34_4",
            "prop_5": "val_34_5",
            "prop_6": "val_34_6",
            "prop_7": "val_34_7",
            "prop_8": "val_34_8",
            "prop_9": "val_34_9",
            "prop_10": "val_34_10",
            "prop_11": "val_34_11",
            "prop_12": "val_34_12",
            "prop_13": "val_34_13",
            "prop_14": "val_34_14",
            "index": 34,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0035",
        "name": "API Gateway Service Benchmark Sample 35",
        "code": "BMK-API-0035",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_35_1",
            "prop_2": "val_35_2",
            "prop_3": "val_35_3",
            "prop_4": "val_35_4",
            "prop_5": "val_35_5",
            "prop_6": "val_35_6",
            "prop_7": "val_35_7",
            "prop_8": "val_35_8",
            "prop_9": "val_35_9",
            "prop_10": "val_35_10",
            "prop_11": "val_35_11",
            "prop_12": "val_35_12",
            "prop_13": "val_35_13",
            "prop_14": "val_35_14",
            "index": 35,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0036",
        "name": "API Gateway Service Benchmark Sample 36",
        "code": "BMK-API-0036",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_36_1",
            "prop_2": "val_36_2",
            "prop_3": "val_36_3",
            "prop_4": "val_36_4",
            "prop_5": "val_36_5",
            "prop_6": "val_36_6",
            "prop_7": "val_36_7",
            "prop_8": "val_36_8",
            "prop_9": "val_36_9",
            "prop_10": "val_36_10",
            "prop_11": "val_36_11",
            "prop_12": "val_36_12",
            "prop_13": "val_36_13",
            "prop_14": "val_36_14",
            "index": 36,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0037",
        "name": "API Gateway Service Benchmark Sample 37",
        "code": "BMK-API-0037",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_37_1",
            "prop_2": "val_37_2",
            "prop_3": "val_37_3",
            "prop_4": "val_37_4",
            "prop_5": "val_37_5",
            "prop_6": "val_37_6",
            "prop_7": "val_37_7",
            "prop_8": "val_37_8",
            "prop_9": "val_37_9",
            "prop_10": "val_37_10",
            "prop_11": "val_37_11",
            "prop_12": "val_37_12",
            "prop_13": "val_37_13",
            "prop_14": "val_37_14",
            "index": 37,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0038",
        "name": "API Gateway Service Benchmark Sample 38",
        "code": "BMK-API-0038",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_38_1",
            "prop_2": "val_38_2",
            "prop_3": "val_38_3",
            "prop_4": "val_38_4",
            "prop_5": "val_38_5",
            "prop_6": "val_38_6",
            "prop_7": "val_38_7",
            "prop_8": "val_38_8",
            "prop_9": "val_38_9",
            "prop_10": "val_38_10",
            "prop_11": "val_38_11",
            "prop_12": "val_38_12",
            "prop_13": "val_38_13",
            "prop_14": "val_38_14",
            "index": 38,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0039",
        "name": "API Gateway Service Benchmark Sample 39",
        "code": "BMK-API-0039",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_39_1",
            "prop_2": "val_39_2",
            "prop_3": "val_39_3",
            "prop_4": "val_39_4",
            "prop_5": "val_39_5",
            "prop_6": "val_39_6",
            "prop_7": "val_39_7",
            "prop_8": "val_39_8",
            "prop_9": "val_39_9",
            "prop_10": "val_39_10",
            "prop_11": "val_39_11",
            "prop_12": "val_39_12",
            "prop_13": "val_39_13",
            "prop_14": "val_39_14",
            "index": 39,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0040",
        "name": "API Gateway Service Benchmark Sample 40",
        "code": "BMK-API-0040",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_40_1",
            "prop_2": "val_40_2",
            "prop_3": "val_40_3",
            "prop_4": "val_40_4",
            "prop_5": "val_40_5",
            "prop_6": "val_40_6",
            "prop_7": "val_40_7",
            "prop_8": "val_40_8",
            "prop_9": "val_40_9",
            "prop_10": "val_40_10",
            "prop_11": "val_40_11",
            "prop_12": "val_40_12",
            "prop_13": "val_40_13",
            "prop_14": "val_40_14",
            "index": 40,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0041",
        "name": "API Gateway Service Benchmark Sample 41",
        "code": "BMK-API-0041",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_41_1",
            "prop_2": "val_41_2",
            "prop_3": "val_41_3",
            "prop_4": "val_41_4",
            "prop_5": "val_41_5",
            "prop_6": "val_41_6",
            "prop_7": "val_41_7",
            "prop_8": "val_41_8",
            "prop_9": "val_41_9",
            "prop_10": "val_41_10",
            "prop_11": "val_41_11",
            "prop_12": "val_41_12",
            "prop_13": "val_41_13",
            "prop_14": "val_41_14",
            "index": 41,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0042",
        "name": "API Gateway Service Benchmark Sample 42",
        "code": "BMK-API-0042",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_42_1",
            "prop_2": "val_42_2",
            "prop_3": "val_42_3",
            "prop_4": "val_42_4",
            "prop_5": "val_42_5",
            "prop_6": "val_42_6",
            "prop_7": "val_42_7",
            "prop_8": "val_42_8",
            "prop_9": "val_42_9",
            "prop_10": "val_42_10",
            "prop_11": "val_42_11",
            "prop_12": "val_42_12",
            "prop_13": "val_42_13",
            "prop_14": "val_42_14",
            "index": 42,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0043",
        "name": "API Gateway Service Benchmark Sample 43",
        "code": "BMK-API-0043",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_43_1",
            "prop_2": "val_43_2",
            "prop_3": "val_43_3",
            "prop_4": "val_43_4",
            "prop_5": "val_43_5",
            "prop_6": "val_43_6",
            "prop_7": "val_43_7",
            "prop_8": "val_43_8",
            "prop_9": "val_43_9",
            "prop_10": "val_43_10",
            "prop_11": "val_43_11",
            "prop_12": "val_43_12",
            "prop_13": "val_43_13",
            "prop_14": "val_43_14",
            "index": 43,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0044",
        "name": "API Gateway Service Benchmark Sample 44",
        "code": "BMK-API-0044",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_44_1",
            "prop_2": "val_44_2",
            "prop_3": "val_44_3",
            "prop_4": "val_44_4",
            "prop_5": "val_44_5",
            "prop_6": "val_44_6",
            "prop_7": "val_44_7",
            "prop_8": "val_44_8",
            "prop_9": "val_44_9",
            "prop_10": "val_44_10",
            "prop_11": "val_44_11",
            "prop_12": "val_44_12",
            "prop_13": "val_44_13",
            "prop_14": "val_44_14",
            "index": 44,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0045",
        "name": "API Gateway Service Benchmark Sample 45",
        "code": "BMK-API-0045",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_45_1",
            "prop_2": "val_45_2",
            "prop_3": "val_45_3",
            "prop_4": "val_45_4",
            "prop_5": "val_45_5",
            "prop_6": "val_45_6",
            "prop_7": "val_45_7",
            "prop_8": "val_45_8",
            "prop_9": "val_45_9",
            "prop_10": "val_45_10",
            "prop_11": "val_45_11",
            "prop_12": "val_45_12",
            "prop_13": "val_45_13",
            "prop_14": "val_45_14",
            "index": 45,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0046",
        "name": "API Gateway Service Benchmark Sample 46",
        "code": "BMK-API-0046",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_46_1",
            "prop_2": "val_46_2",
            "prop_3": "val_46_3",
            "prop_4": "val_46_4",
            "prop_5": "val_46_5",
            "prop_6": "val_46_6",
            "prop_7": "val_46_7",
            "prop_8": "val_46_8",
            "prop_9": "val_46_9",
            "prop_10": "val_46_10",
            "prop_11": "val_46_11",
            "prop_12": "val_46_12",
            "prop_13": "val_46_13",
            "prop_14": "val_46_14",
            "index": 46,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0047",
        "name": "API Gateway Service Benchmark Sample 47",
        "code": "BMK-API-0047",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_47_1",
            "prop_2": "val_47_2",
            "prop_3": "val_47_3",
            "prop_4": "val_47_4",
            "prop_5": "val_47_5",
            "prop_6": "val_47_6",
            "prop_7": "val_47_7",
            "prop_8": "val_47_8",
            "prop_9": "val_47_9",
            "prop_10": "val_47_10",
            "prop_11": "val_47_11",
            "prop_12": "val_47_12",
            "prop_13": "val_47_13",
            "prop_14": "val_47_14",
            "index": 47,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0048",
        "name": "API Gateway Service Benchmark Sample 48",
        "code": "BMK-API-0048",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_48_1",
            "prop_2": "val_48_2",
            "prop_3": "val_48_3",
            "prop_4": "val_48_4",
            "prop_5": "val_48_5",
            "prop_6": "val_48_6",
            "prop_7": "val_48_7",
            "prop_8": "val_48_8",
            "prop_9": "val_48_9",
            "prop_10": "val_48_10",
            "prop_11": "val_48_11",
            "prop_12": "val_48_12",
            "prop_13": "val_48_13",
            "prop_14": "val_48_14",
            "index": 48,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0049",
        "name": "API Gateway Service Benchmark Sample 49",
        "code": "BMK-API-0049",
        "status": "DRAFT",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_49_1",
            "prop_2": "val_49_2",
            "prop_3": "val_49_3",
            "prop_4": "val_49_4",
            "prop_5": "val_49_5",
            "prop_6": "val_49_6",
            "prop_7": "val_49_7",
            "prop_8": "val_49_8",
            "prop_9": "val_49_9",
            "prop_10": "val_49_10",
            "prop_11": "val_49_11",
            "prop_12": "val_49_12",
            "prop_13": "val_49_13",
            "prop_14": "val_49_14",
            "index": 49,
            "enabled": True
        }
    },
    {
        "id": "fixture-api_gateway-0050",
        "name": "API Gateway Service Benchmark Sample 50",
        "code": "BMK-API-0050",
        "status": "ACTIVE",
        "category": "BENCHMARK",
        "attributes": {
            "prop_1": "val_50_1",
            "prop_2": "val_50_2",
            "prop_3": "val_50_3",
            "prop_4": "val_50_4",
            "prop_5": "val_50_5",
            "prop_6": "val_50_6",
            "prop_7": "val_50_7",
            "prop_8": "val_50_8",
            "prop_9": "val_50_9",
            "prop_10": "val_50_10",
            "prop_11": "val_50_11",
            "prop_12": "val_50_12",
            "prop_13": "val_50_13",
            "prop_14": "val_50_14",
            "index": 50,
            "enabled": True
        }
    },
]
